version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: postgres_library

    restart: always

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./springboot-library

    container_name: springboot_library

    restart: always

    depends_on:
      - postgres

    ports:
      - "8098:8098"

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./library-sigeb

    container_name: vue_library

    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  postgres_data:
