server.port=8098

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

app.certificados.ruta-base=/app/uploads/certificados

app.storage.tipos.portadas.ruta-base=/app/uploads/portadas
app.storage.tipos.portadas.url-base=/portadas

app.storage.tipos.logos.ruta-base=/app/uploads/logos
app.storage.tipos.logos.url-base=/logos

app.storage.tipos.pdfs.ruta-base=/app/uploads/pdfs
app.storage.tipos.pdfs.url-base=/pdfs

app.storage.tipos.respaldos_encargados.ruta-base=/app/uploads/respaldos_encargados
app.storage.tipos.respaldos_encargados.url-base=/respaldos_encargados

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.task.scheduling.pool.size=3

spring.jackson.time-zone=America/La_Paz